# Generated by Django 5.2.3 on 2026-03-05 01:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Атауы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модульдер',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='MatchingColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(verbose_name='Атауы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілігі')),
            ],
            options={
                'verbose_name': 'Сәйкес баған',
                'verbose_name_plural': 'Сәйкес бағандар',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сұрақ')),
                ('question_type', models.CharField(choices=[('simple', 'Бір жауапты'), ('multiple', 'Көп жауапты')], default='simple', max_length=32, verbose_name='Сұрақтың түрі')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
            ],
            options={
                'verbose_name': 'Тест сұрағы',
                'verbose_name_plural': 'Тест сұрақтары',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='core/account/users/', verbose_name='Сурет')),
                ('user_type', models.CharField(choices=[('student', 'Білім алушы'), ('teacher', 'Оқытушы'), ('admin', 'Администрация')], default='student', max_length=32, verbose_name='Қолданушы типі')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Қолданушы',
                'verbose_name_plural': 'Қолданушылар',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Соңғы жаңарту')),
                ('lab_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Виртуалды лаборатория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.chapter', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Сабақ',
                'verbose_name_plural': 'Сабақтар',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LessonDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('file', models.FileField(blank=True, null=True, upload_to='core/models/lesson/docs/', verbose_name='Файл')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Сабақ құжаты',
                'verbose_name_plural': 'Сабақ құжаттары',
            },
        ),
        migrations.CreateModel(
            name='MatchingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Жауабы')),
                ('correct_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_items', to='core.matchingcolumn', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Сәйкес элемент',
                'verbose_name_plural': 'Сәйкес элементтер',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Жауап')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс жауап')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Балл')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Жауап',
                'verbose_name_plural': 'Жауаптар',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Атауы')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='core/models/subject/posters', verbose_name='Постер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Уақыты')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Соңғы өзгеріс')),
                ('view', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Қаралым')),
                ('cert', models.FileField(blank=True, null=True, upload_to='core/models/subject/certs', verbose_name='Сертификат')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Пән',
                'verbose_name_plural': 'Пәндер',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.subject', verbose_name='Пән'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.subject', verbose_name='Пән'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('video', 'Видеосабақ'), ('written', 'Жазбаша'), ('test', 'Тест'), ('matching', 'Сәйкестендіру')], default='video', max_length=32, verbose_name='Тапсырма түрі')),
                ('params', models.CharField(choices=[('none', 'Таңдалмаған'), ('Тест', [('quiz', 'Тест'), ('true-false', 'Ақиқат/жалған')]), ('Сәйкестендіру', [('row', 'Қатар'), ('col', 'Баған')]), ('lab', 'Виртуалды лаборатория')], default='none', max_length=32, verbose_name='Параметрлер')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Жалпы бағасы')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Тапсырма уақыты (мин)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтамасы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.lesson', verbose_name='Сабақ')),
            ],
            options={
                'verbose_name': 'Тапсырма',
                'verbose_name_plural': 'Тапсырмалар',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.task', verbose_name='Тапсырма'),
        ),
        migrations.AddField(
            model_name='matchingcolumn',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.task', verbose_name='Тапсырма'),
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы бағасы')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Пайыздық мөлшері')),
                ('status', models.CharField(choices=[('no-started', 'Сабақ басталмады'), ('in-progress', 'Сабақ өтілуде'), ('finished', 'Сабақ аяқталды')], default='no-started', max_length=64, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Орындалған уақыты')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='core.lesson', verbose_name='Сабақ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушының сабағы',
                'verbose_name_plural': 'Қолданушының сабақтары',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Өте нашар'), (2, 'Нашар'), (3, 'Орташа'), (4, 'Жақсы'), (5, 'Тамаша')], verbose_name='Бағасы')),
                ('comment', models.TextField(blank=True, verbose_name='Пікір')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жазылған уақыты')),
                ('user_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.userlesson', verbose_name='Қолданушының сабағы')),
            ],
            options={
                'verbose_name': 'Кері байланыс',
                'verbose_name_plural': 'Кері байланыстар',
            },
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы бағасы')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Пайыздық мөлшері')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Басталған уақыты')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Орындалған уақыты')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to='core.subject', verbose_name='Пән')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Қолданушының пәні',
                'verbose_name_plural': 'Қолданушының пәндері',
            },
        ),
        migrations.AddField(
            model_name='userlesson',
            name='user_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='core.usersubject', verbose_name='Қолданушының пәні'),
        ),
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы бағасы')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Пайыздық мөлшері')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to='core.chapter', verbose_name='Бөлім')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chapters', to='core.usersubject', verbose_name='Қолданушының пәндері')),
            ],
            options={
                'verbose_name': 'Қолданушының пән бөлімі',
                'verbose_name_plural': 'Қолданушының пән бөлімдері',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыты')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Жалпы бағасы')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='core.task', verbose_name='Тапсырма')),
                ('user_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='core.userlesson', verbose_name='Қолданушының сабағы')),
            ],
            options={
                'verbose_name': 'Қолданушының тапсырмасы',
                'verbose_name_plural': 'Қолданушының тапсырмалары',
            },
        ),
        migrations.CreateModel(
            name='UserMatchingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс жауап')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matchingitem', verbose_name='Жауап')),
                ('selected_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.matchingcolumn', verbose_name='Баған')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_answers', to='core.usertask', verbose_name='Қолданушының тапсырмасы')),
            ],
            options={
                'verbose_name': 'Қолданушының сәйкестендіруі',
                'verbose_name_plural': 'Қолданушының сәйкестендірулері',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.ManyToManyField(related_name='user_answers', to='core.option', verbose_name='Таңдалған жауаптар')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_options', to='core.question', verbose_name='Жауап')),
                ('user_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_options', to='core.usertask', verbose_name='Қолданушы тапсырмасы')),
            ],
            options={
                'verbose_name': 'Таңдалған жауап',
                'verbose_name_plural': 'Таңдалған жауаптар',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(verbose_name='URL сілтеме')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.task', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Видеосабақ',
                'verbose_name_plural': 'Видеосабақтар',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='Қараған уақыт (сек)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Аяқталған')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='core.usertask', verbose_name='Қолданушының тапсырмасы')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_videos', to='core.video', verbose_name='Видеосабақ')),
            ],
            options={
                'verbose_name': 'Қолданушының видеосабағы',
                'verbose_name_plural': 'Қолданушының видеосабақтары',
            },
        ),
        migrations.CreateModel(
            name='Written',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='Тапсырма')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Жазбаша',
                'verbose_name_plural': 'Жазбашалар',
            },
        ),
        migrations.CreateModel(
            name='UserWritten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='core/models/user_written/files/', verbose_name='Файл')),
                ('answer', models.TextField(verbose_name='Жауабы')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Жіберілді')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_written', to='core.usertask', verbose_name='Қолданушының тапсырмасы')),
                ('written', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_written', to='core.written', verbose_name='Жазбаша')),
            ],
            options={
                'verbose_name': 'Қолданушының жазбаша жауабы',
                'verbose_name_plural': 'Қолданушының жазбаша жауаптары',
            },
        ),
    ]
