# Generated by Django 5.2.3 on 2026-03-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subject_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='view',
        ),
    ]
