# Generated by Django 5.2.3 on 2026-03-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subject_cert_remove_subject_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lab_link',
        ),
    ]
