# Generated by Django 5.2.3 on 2026-03-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_lesson_lab_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermatchinganswer',
            name='selected_column',
        ),
        migrations.RemoveField(
            model_name='matchingitem',
            name='correct_column',
        ),
        migrations.RemoveField(
            model_name='usermatchinganswer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='usermatchinganswer',
            name='user_task',
        ),
        migrations.RemoveField(
            model_name='userwritten',
            name='user_task',
        ),
        migrations.RemoveField(
            model_name='userwritten',
            name='written',
        ),
        migrations.RemoveField(
            model_name='written',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='params',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('theory', 'Теория'), ('video', 'Видеосабақ'), ('test', 'Тестілеу'), ('simulator', 'Симулятор')], default='theory', max_length=32, verbose_name='Тапсырма түрі'),
        ),
        migrations.DeleteModel(
            name='MatchingColumn',
        ),
        migrations.DeleteModel(
            name='MatchingItem',
        ),
        migrations.DeleteModel(
            name='UserMatchingAnswer',
        ),
        migrations.DeleteModel(
            name='UserWritten',
        ),
        migrations.DeleteModel(
            name='Written',
        ),
    ]
