# Generated by Django 5.2.3 on 2026-03-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usermatchinganswer_selected_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Пайыздық мөлшері'),
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Атауы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Қысқаша сипаттама')),
                ('url', models.TextField(blank=True, null=True, verbose_name='URL сілтеме')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulators', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Симулятор',
                'verbose_name_plural': 'Симуляторлар',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Теория мәтіні')),
                ('file', models.FileField(blank=True, null=True, upload_to='theory/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік нөмері')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theories', to='core.task', verbose_name='Тапсырма')),
            ],
            options={
                'verbose_name': 'Теория',
                'verbose_name_plural': 'Теориялар',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='UserSimulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Орындалды')),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_simulators', to='core.simulator', verbose_name='Симулятор')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_simulators', to='core.usertask', verbose_name='Қолданушының тапсырмасы')),
            ],
            options={
                'verbose_name': 'Қолданушының симуляторы',
                'verbose_name_plural': 'Қолданушының симуляторлары',
            },
        ),
        migrations.CreateModel(
            name='UserTheory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Оқылды')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_theories', to='core.theory', verbose_name='Теория')),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_theories', to='core.usertask', verbose_name='Қолданушының тапсырмасы')),
            ],
            options={
                'verbose_name': 'Қолданушының теориясы',
                'verbose_name_plural': 'Қолданушының теориялары',
            },
        ),
    ]
