# Generated by Django 5.2.3 on 2026-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usertask_percentage_simulator_theory_usersimulator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulator',
            name='description',
        ),
        migrations.RemoveField(
            model_name='simulator',
            name='title',
        ),
        migrations.AlterField(
            model_name='simulator',
            name='url',
            field=models.TextField(default=1, verbose_name='URL сілтеме'),
            preserve_default=False,
        ),
    ]
