# Generated by Django 5.2.3 on 2026-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_simulator_description_remove_simulator_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='url',
            field=models.CharField(max_length=300, verbose_name='URL сілтеме'),
        ),
    ]
