# Generated by Django 5.2.3 on 2026-03-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_simulator_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
