# Generated by Django 5.2.3 on 2026-04-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_email_verification_and_security_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Сәтті кіру'), ('login_failed', 'Сәтсіз кіру'), ('logout', 'Шығу'), ('register', 'Тіркелу'), ('password_reset_requested', 'Құпия сөзді қалпына келтіру сұралады'), ('password_reset_completed', 'Құпия сөзді қалпына келтіру аяқталды'), ('password_changed', 'Құпиясөз өзгертілді'), ('account_deleted', 'Аккаунт жойылды'), ('profile_updated', 'Профиль жаңартылды'), ('email_verification_sent', 'Электрондық поштаны тексеру жіберілді'), ('email_verified', 'Электрондық пошта расталды')], max_length=64, verbose_name='Оқиға түрі'),
        ),
    ]
