# Generated by Django 5.2.3 on 2026-04-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_securityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Backup codes'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA қосулы'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='OTP secret'),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Сәтті кіру'), ('login_failed', 'Сәтсіз кіру'), ('logout', 'Шығу'), ('register', 'Тіркелу'), ('password_reset_requested', 'Құпия сөзді қалпына келтіру сұралады'), ('password_reset_completed', 'Құпия сөзді қалпына келтіру аяқталды'), ('password_changed', 'Құпиясөз өзгертілді'), ('account_deleted', 'Аккаунт жойылды'), ('profile_updated', 'Профиль жаңартылды'), ('email_verification_sent', 'Электрондық поштаны тексеру жіберілді'), ('email_verified', 'Электрондық пошта расталды'), ('2fa_enabled', '2FA қосулы'), ('2fa_disabled', '2FA өшірулі'), ('2fa_challenge_passed', '2FA процесінен өтті'), ('2fa_challenge_failed', '2FA процесінде қателік кетті'), ('2fa_backup_code_used', '2FA Backup Code Used')], max_length=64, verbose_name='Оқиға түрі'),
        ),
    ]
