# Generated by Django 5.2.3 on 2026-04-19 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_backup_codes_user_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Құрылғы атауы')),
                ('credential_id', models.CharField(max_length=512, unique=True, verbose_name='Credential ID')),
                ('public_key', models.TextField(verbose_name='Public key')),
                ('sign_count', models.PositiveBigIntegerField(default=0, verbose_name='Sign count')),
                ('transports', models.JSONField(blank=True, default=list, verbose_name='Transports')),
                ('aaguid', models.CharField(blank=True, max_length=64, verbose_name='AAGUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Соңғы қолданылған уақыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL, verbose_name='Қолданушы')),
            ],
            options={
                'verbose_name': 'Passkey credential',
                'verbose_name_plural': 'Passkey credentials',
                'ordering': ('-created_at',),
            },
        ),
    ]
