# Generated by Django 5.2.3 on 2026-06-09 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_passkeycredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Атауы')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('youtube_url', models.URLField(verbose_name='YouTube сілтемесі')),
                ('embed_url', models.URLField(blank=True, verbose_name='Embed сілтемесі')),
                ('starts_at', models.DateTimeField(verbose_name='Басталу уақыты')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Аяқталу уақыты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='core.subject', verbose_name='Пән')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL, verbose_name='Оқытушы')),
            ],
            options={
                'verbose_name': 'Тікелей эфир',
                'verbose_name_plural': 'Тікелей эфирлер',
                'ordering': ['starts_at'],
            },
        ),
    ]
