# Generated by Django 5.2.3 on 2026-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_livestream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='embed_url',
        ),
        migrations.AddField(
            model_name='livestream',
            name='iframe_code',
            field=models.TextField(default=1, verbose_name='YouTube iframe коды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestream',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube сілтемесі'),
        ),
    ]
